name: CI
on:
  push:
    branches: [master]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 레파지토리 check out
      - name: Checkout source code.
        uses: actions/checkout@v2

      # node.js 버전 12
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # 의존 파일 설치
      - name: Install Dependencies
        run: npm install

      # 빌드
      - name: Build
        run: npm run build

      # 폴더 이름 변경
      - name: Change name build to docs
        run: mv build docs

      # Stash
      - name: Stash docs at master
        run: git stash

      # release 브랜치 이동
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'release'
          commit_message: 'Build done!'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Stash 적용
      - name: Apply Stash at release
        run: git stash pop
